Singular value Decomposition(SVD) Example

In [21]:
import numpy as np
np.set_printoptions(precision=4,suppress=True)

In [22]:
a= np.array([[1,2,3,4],[1,1,2,3],[0,1,1,0]])
print(a)

[[1 2 3 4]
 [1 1 2 3]
 [0 1 1 0]]


SVD Method

In [23]:
u,s,vh= np.linalg.svd(a, full_matrices=True)

In [24]:
u.shape, s.shape, vh.shape

((3, 3), (3,), (4, 4))

u, vh is orthonormal

In [25]:
u
u.dot(u.T)

array([[ 1.,  0.,  0.],
       [ 0.,  1., -0.],
       [ 0., -0.,  1.]])

In [26]:
vh
vh.dot(vh.T)

array([[ 1., -0.,  0.,  0.],
       [-0.,  1.,  0., -0.],
       [ 0.,  0.,  1., -0.],
       [ 0., -0., -0.,  1.]])

In [27]:
s

array([6.7509, 1.1734, 0.2186])

In [28]:
s=[6.7509, 1.1734, 0.2186]

Since s is given as a 3 element array, we need to reshape it into a 3X4 array with 3 elements along its diagonal

In [29]:
sd= np.diag(s) #makes a 3 x 3 diagonal matrix

In [30]:
sd.shape

(3, 3)

In [31]:
b= np.zeros((3,4))

In [32]:
b[:,:-1]=sd
b

array([[6.7509, 0.    , 0.    , 0.    ],
       [0.    , 1.1734, 0.    , 0.    ],
       [0.    , 0.    , 0.2186, 0.    ]])

In [33]:
sigma =b
sigma

array([[6.7509, 0.    , 0.    , 0.    ],
       [0.    , 1.1734, 0.    , 0.    ],
       [0.    , 0.    , 0.2186, 0.    ]])

In [36]:
print(np.dot(np.dot(u,sigma),vh))

[[ 1.  2.  3.  4.]
 [ 1.  1.  2.  3.]
 [-0.  1.  1.  0.]]
